[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/info"
healthcheckTimeout = 100

[deploy.railway.frontend]
startCommand = "cd frontend && npm run build && npm run preview"